# Generated by Django 4.1.2 on 2022-11-19 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='tags',
            new_name='Hashtags',
        ),
    ]
